version: "3.9"

services:
  tokenizer:
    hostname: tokenizer
    container_name: tokenizer
    image: tokenizer:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - ./static:/hotdeal-tokenizer/static
    ports:
      - "8000:8000"