# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenizer_definition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atokenizer_definition.proto\"\"\n\x11TokenizingRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\"\n\x10TokenizingResult\x12\x0e\n\x06tokens\x18\x01 \x03(\t2@\n\tTokenizer\x12\x33\n\x08Tokenize\x12\x12.TokenizingRequest\x1a\x11.TokenizingResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenizer_definition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TOKENIZINGREQUEST']._serialized_start=30
  _globals['_TOKENIZINGREQUEST']._serialized_end=64
  _globals['_TOKENIZINGRESULT']._serialized_start=66
  _globals['_TOKENIZINGRESULT']._serialized_end=100
  _globals['_TOKENIZER']._serialized_start=102
  _globals['_TOKENIZER']._serialized_end=166
# @@protoc_insertion_point(module_scope)
